stages:
  train_gpr:
    cmd: python src/train_gpr.py data/df_high.csv model_gpr.pth
    deps:
    - data/df_high.csv
    - src/train_gpr.py
    params:
    - train_gpr.num_iterations
    outs:
    - model_gpr.pth
