stages:
  train_gpr:
    cmd: python src/gpr_train.py datadf_high.csv model_gpr.pth
    deps:
    - datadf_high.csv
    - src/train_gpr.py
    params:
    - num_iterations
    outs:
    - model_gpr.pth
