stages:
  prepare_ratio_gpr:
    cmd: python src/prepare_ratio_gpr.py data/df_high.csv data/prepared/
    deps:
    - data/df_high.csv
    - src/prepare_ratio_gpr.py
    outs:
    - data/prepared/ratio_gpr_train_data.pt
    - data/prepared/ratio_gpr_test_data.pt
    - data/prepared/ratio_gpr_scaler.pkl

  train_ratio_gpr:
    cmd: python src/train_gpr.py data/prepared/ratio_gpr_train_data.pt  models/model_state_ratio_gpr.pth
    deps:
    - data/prepared/ratio_gpr_train_data.pt
    - src/train_gpr.py
    params:
    - train_ratio_gpr
    outs:
    - models/model_state_ratio_gpr.pth

  evaluate_ratio_gpr:
    cmd: python src/evaluate_gpr.py models/model_state_ratio_gpr.pth data/prepared/ratio_gpr_test_data.pt
      eval/ratio_gpr
    deps:
    - data/prepared/ratio_gpr_test_data.pt
    - models/model_state_ratio_gpr.pth
    - src/evaluate_gpr.py

  prepare_base_gpr:
    cmd: python src/prepare_base_gpr.py data/df_high.csv data/prepared/
    deps:
    - data/df_high.csv
    - src/prepare_base_gpr.py
    outs:
    - data/prepared/base_gpr_train_data.pt
    - data/prepared/base_gpr_test_data.pt

  train_base_gpr:
    cmd: python src/train_gpr.py data/prepared/base_gpr_train_data.pt models/model_state_base_gpr.pth
    deps:
    - data/prepared/base_gpr_train_data.pt
    - src/train_gpr.py
    params:
    - train_base_gpr
    outs:
    - models/model_state_base_gpr.pth

  evaluate_base_gpr:
    cmd: python src/evaluate_gpr.py models/model_state_base_gpr.pth data/prepared/base_gpr_test_data.pt
      eval/base_gpr
    deps:
    - data/prepared/base_gpr_test_data.pt
    - models/model_state_base_gpr.pth
    - src/evaluate_gpr.py


  prepare_gpr:
    cmd: python src/prepare_gpr.py data/df_high.csv data/prepared/
    deps:
    - data/df_high.csv
    - src/prepare_gpr.py
    outs:
    - data/prepared/gpr_train_data.pt
    - data/prepared/gpr_test_data.pt

  train_gpr:
    cmd: python src/train_gpr.py data/prepared/gpr_train_data.pt models/model_state_gpr.pth
    deps:
    - data/prepared/gpr_train_data.pt
    - src/train_gpr.py
    params:
    - train_gpr
    outs:
    - models/model_state_gpr.pth

  evaluate_gpr:
    cmd: python src/evaluate_gpr.py models/model_state_gpr.pth data/prepared/gpr_test_data.pt
      eval/gpr/
    deps:
    - data/prepared/gpr_test_data.pt
    - models/model_state_gpr.pth
    - src/evaluate_gpr.py


metrics:
- eval/ratio_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/base_gpr/metrics.json
- eval/ratio_gpr/metrics.json
- eval/base_gpr/metrics.json
- eval/gpr/metrics.json
plots:
- eval/ratio_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/base_gpr/plots/images
- eval/ratio_gpr/plots/images
- eval/base_gpr/plots/images
- eval/gpr/plots/images
